services:
  oxigraph:
    image: ghcr.io/oxigraph/oxigraph
    ports:
      - "7878:7878"
    volumes:
      - oxigraph-data:/data
    command: serve --location /data --bind 0.0.0.0:7878

volumes:
  oxigraph-data:
