export function generatePostEditHookScript(): string {
  return `#!/usr/bin/env node
// Generated by: opentology context init
// PostToolUse hook — incremental symbol scan after source file edits
import { existsSync, writeFileSync, unlinkSync, statSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, resolve, dirname, extname } from 'node:path';

const SOURCE_EXTENSIONS = new Set([
  '.ts', '.js', '.tsx', '.jsx',
  '.py', '.go', '.rs', '.java', '.swift',
]);

const DEBOUNCE_MS = 30_000;

function findProjectRoot(startDir) {
  let dir = resolve(startDir);
  while (dir !== dirname(dir)) {
    if (existsSync(join(dir, '.opentology.json'))) return dir;
    dir = dirname(dir);
  }
  return null;
}

function findBin(projectRoot) {
  const local = join(projectRoot, 'node_modules', '.bin', 'opentology');
  if (existsSync(local)) return { bin: local, args: [] };
  return { bin: 'npx', args: ['opentology'] };
}

const projectRoot = findProjectRoot(process.cwd());
if (!projectRoot) process.exit(0);

// Read hook input from stdin
let input = '';
process.stdin.setEncoding('utf-8');
process.stdin.on('data', chunk => { input += chunk; });
process.stdin.on('end', () => {
  try {
    const event = JSON.parse(input || '{}');
    const toolName = event.tool_name || event.toolName || '';
    const filePath = event.tool_input?.file_path || event.tool_input?.path || '';

    // Only trigger on edit/write tools
    if (!/Edit|Write|MultiEdit/i.test(toolName)) process.exit(0);

    // Only trigger on source file extensions
    if (filePath && !SOURCE_EXTENSIONS.has(extname(filePath).toLowerCase())) process.exit(0);

    // Debounce: skip if scan-lock exists and is recent
    const lockFile = join(projectRoot, '.opentology', '.scan-lock');
    if (existsSync(lockFile)) {
      const age = Date.now() - statSync(lockFile).mtimeMs;
      if (age < DEBOUNCE_MS) process.exit(0);
    }

    // Acquire lock
    writeFileSync(lockFile, String(Date.now()), 'utf-8');

    const { bin, args } = findBin(projectRoot);
    try {
      execFileSync(bin, [...args, 'context', 'scan', '--depth', 'symbol', '--incremental'], {
        cwd: projectRoot,
        timeout: 30_000,
        stdio: 'ignore',
      });
    } catch {
      // Non-blocking — never fail the hook
    } finally {
      try { unlinkSync(lockFile); } catch { /* ignore */ }
    }
  } catch {
    // Malformed input — exit cleanly
  }
  process.exit(0);
});
`;
}
