export function generatePreEditHookScript(): string {
  return `#!/usr/bin/env node
// Generated by: opentology context init
// PreToolUse hook — queries impact analysis before Edit/Write
import { existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, resolve, dirname } from 'node:path';

const TIMEOUT = parseInt(process.env.OPENTOLOGY_HOOK_TIMEOUT || '3000', 10);

function findProjectRoot(startDir) {
  let dir = resolve(startDir);
  while (dir !== dirname(dir)) {
    if (existsSync(join(dir, '.opentology.json'))) return dir;
    dir = dirname(dir);
  }
  return null;
}

function findBin(projectRoot) {
  const local = join(projectRoot, 'node_modules', '.bin', 'opentology');
  if (existsSync(local)) return { bin: local, args: [] };
  return { bin: 'npx', args: ['opentology'] };
}

function run(projectRoot, cmdArgs) {
  const { bin, args } = findBin(projectRoot);
  return execFileSync(bin, [...args, ...cmdArgs], {
    cwd: projectRoot,
    timeout: TIMEOUT,
    encoding: 'utf-8',
    stdio: ['pipe', 'pipe', 'pipe'],
  });
}

try {
  const projectRoot = findProjectRoot(process.cwd());
  if (!projectRoot) process.exit(0);

  // Parse tool input from stdin (Claude Code passes JSON via stdin for hooks)
  let input = '';
  try {
    input = require('fs').readFileSync('/dev/stdin', 'utf-8');
  } catch {
    process.exit(0);
  }

  let toolInput;
  try {
    toolInput = JSON.parse(input);
  } catch {
    process.exit(0);
  }

  // Extract file path from Edit or Write tool arguments
  const filePath = toolInput?.tool_input?.file_path;
  if (!filePath) process.exit(0);

  // Convert absolute path to project-relative path
  const relative = filePath.startsWith(projectRoot)
    ? filePath.slice(projectRoot.length + 1)
    : filePath;

  // Skip non-source files
  if (relative.startsWith('node_modules/') || relative.startsWith('.')) process.exit(0);

  const raw = run(projectRoot, ['context', 'impact', '--file', relative, '--format', 'json']);
  const data = JSON.parse(raw);

  // Only output if there are meaningful dependencies
  if (data.dependents?.length > 0 || data.related?.length > 0) {
    const lines = [];
    lines.push(\`[Impact Analysis] \${relative}\`);

    if (data.dependents.length > 0) {
      lines.push(\`Dependents (\${data.dependents.length}): \${data.dependents.slice(0, 5).join(', ')}\${data.dependents.length > 5 ? '...' : ''}\`);
    }

    if (data.dependencies?.length > 0) {
      lines.push(\`Dependencies (\${data.dependencies.length}): \${data.dependencies.slice(0, 5).join(', ')}\${data.dependencies.length > 5 ? '...' : ''}\`);
    }

    if (data.related?.length > 0) {
      lines.push('Related:');
      for (const r of data.related.slice(0, 3)) {
        lines.push(\`  - [\${r.type}] \${r.title}\${r.status ? ' (' + r.status + ')' : ''}\`);
      }
    }

    if (data.impact === 'high') {
      lines.push('\\u26a0\\ufe0f HIGH IMPACT — multiple modules depend on this file. Review dependents before making breaking changes.');
    }

    console.log(lines.join('\\n'));
  }
} catch {
  // Silent exit — do not block editing
  process.exit(0);
}
`;
}
