export function generateStopSessionHookScript(): string {
  return `#!/usr/bin/env node
// Generated by: opentology context init
// Stop hook — reminds LLM to push session log and knowledge triples
import { existsSync } from 'node:fs';
import { execSync, execFileSync } from 'node:child_process';
import { join, resolve, dirname } from 'node:path';

const TIMEOUT = parseInt(process.env.OPENTOLOGY_HOOK_TIMEOUT || '5000', 10);

function findProjectRoot(startDir) {
  let dir = resolve(startDir);
  while (dir !== dirname(dir)) {
    if (existsSync(join(dir, '.opentology.json'))) return dir;
    dir = dirname(dir);
  }
  return null;
}

function findBin(projectRoot) {
  const local = join(projectRoot, 'node_modules', '.bin', 'opentology');
  if (existsSync(local)) return { bin: local, args: [] };
  return { bin: 'npx', args: ['opentology'] };
}

function run(projectRoot, cmdArgs) {
  const { bin, args } = findBin(projectRoot);
  return execFileSync(bin, [...args, ...cmdArgs], {
    cwd: projectRoot,
    timeout: TIMEOUT,
    encoding: 'utf-8',
    stdio: ['pipe', 'pipe', 'pipe'],
  });
}

try {
  const projectRoot = findProjectRoot(process.cwd());
  if (!projectRoot) process.exit(0);

  // Check recent commits (last 2 hours)
  let log = '';
  try {
    log = execSync('git log --since="2 hours ago" --oneline', {
      cwd: projectRoot, encoding: 'utf-8', timeout: 3000,
    }).trim();
  } catch { process.exit(0); }

  if (!log) process.exit(0);

  const commitCount = log.split('\\n').length;
  // Check if source code was changed (not just docs/config)
  let srcChanged = false;
  try {
    const diff = execSync('git diff HEAD~' + Math.min(commitCount, 10) + ' --name-only 2>/dev/null', {
      cwd: projectRoot, encoding: 'utf-8', timeout: 3000,
    }).trim();
    srcChanged = diff.split('\\n').some(f => f.startsWith('src/') || f.startsWith('lib/') || f.endsWith('.ts') || f.endsWith('.py') || f.endsWith('.go'));
  } catch { srcChanged = commitCount >= 2; }

  // Importance: high (3+ commits or src changes), medium (1-2 commits), low (0)
  const importance = (commitCount >= 3 || srcChanged) ? 'high' : commitCount >= 1 ? 'medium' : 'low';
  if (importance === 'low') process.exit(0);

  // Check if session log already exists for today
  const today = new Date().toISOString().slice(0, 10);
  let sessionExists = false;
  try {
    const raw = run(projectRoot, [
      'query', '--format', 'json',
      'PREFIX otx: <https://opentology.dev/vocab#> ASK WHERE { ?s a otx:Session ; otx:date "' + today + '"^^<http://www.w3.org/2001/XMLSchema#date> }'
    ]);
    sessionExists = raw.includes('true');
  } catch { /* query failed, assume not exists */ }

  const reminders = [];

  if (!sessionExists) {
    reminders.push('Push an otx:Session summary to the sessions graph (title, date, body, nextTodo).');
  }

  // Always remind about Knowledge/Decision/Issue recording
  reminders.push('Review if any of these should be recorded:');
  reminders.push('- Architecture/tech decisions → otx:Decision');
  reminders.push('- Reusable patterns or lessons → otx:Knowledge');
  reminders.push('- Resolved bugs/issues → otx:Issue');
  reminders.push('- External sources ingested → otx:Source');

  if (reminders.length > 0) {
    const header = sessionExists
      ? 'Session log exists. Check if additional knowledge should be recorded:'
      : 'Session log missing (' + today + ', ' + commitCount + ' commits, importance: ' + importance + '). Before ending:';
    console.log(header);
    for (const r of reminders) console.log('  ' + r);
  }
} catch {
  process.exit(0);
}
`;
}
