export function generateUserPromptHookScript(): string {
  return `#!/usr/bin/env node
// Generated by: opentology context init
// UserPromptSubmit hook — extracts keywords from user message and queries related context
import { existsSync, readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, resolve, dirname } from 'node:path';

const TIMEOUT = parseInt(process.env.OPENTOLOGY_HOOK_TIMEOUT || '3000', 10);

// Stop words (EN + KO common particles/connectors)
const STOP_WORDS = new Set([
  // English
  'the','a','an','is','are','was','were','be','been','being','have','has','had',
  'do','does','did','will','would','shall','should','may','might','must','can','could',
  'this','that','these','those','it','its','i','you','he','she','we','they','me','him',
  'her','us','them','my','your','his','our','their','what','which','who','whom','when',
  'where','why','how','not','no','nor','but','and','or','if','then','else','for','from',
  'with','without','about','above','after','before','between','into','through','during',
  'to','of','in','on','at','by','as','so','than','too','very','just','also','now','here',
  'there','all','each','every','both','few','more','most','other','some','such','only',
  'same','let','please','want','need','like','make','get','use','try','look','see','know',
  'think','help','show','tell','give','take','come','go','run','file','code','check',
  // Korean particles/connectors
  '은','는','이','가','을','를','에','에서','으로','로','와','과','의','도','만',
  '부터','까지','에게','한테','보다','라고','이라고','하고','해서','해줘','해주세요',
  '좀','그','저','것','거','수','때','중','후','전','안','못','잘','더','다',
  '뭐','어떻게','왜','어디','언제','누가','뭘','걸','건','데','게','줘',
]);

function findProjectRoot(startDir) {
  let dir = resolve(startDir);
  while (dir !== dirname(dir)) {
    if (existsSync(join(dir, '.opentology.json'))) return dir;
    dir = dirname(dir);
  }
  return null;
}

function findBin(projectRoot) {
  const local = join(projectRoot, 'node_modules', '.bin', 'opentology');
  if (existsSync(local)) return { bin: local, args: [] };
  return { bin: 'npx', args: ['opentology'] };
}

function run(projectRoot, cmdArgs) {
  const { bin, args } = findBin(projectRoot);
  return execFileSync(bin, [...args, ...cmdArgs], {
    cwd: projectRoot,
    timeout: TIMEOUT,
    encoding: 'utf-8',
    stdio: ['pipe', 'pipe', 'pipe'],
  });
}

function extractKeywords(text) {
  const keywords = [];

  // Step 1: Split mixed Korean+English tokens (e.g. "persistGraph에서" → "persistGraph", "에서")
  const raw = text.replace(/[\\n\\r]/g, ' ');
  const mixedSplit = raw.replace(/([a-zA-Z0-9_./]+)([\\uAC00-\\uD7AF\\u3130-\\u318F]+)/g, '$1 $2')
                        .replace(/([\\uAC00-\\uD7AF\\u3130-\\u318F]+)([a-zA-Z0-9_./]+)/g, '$1 $2');

  const tokens = mixedSplit
    .split(/[\\s,.:;!?()\\[\\]{}'"]+/)
    .filter(Boolean);

  for (const token of tokens) {
    const lower = token.toLowerCase();
    if (STOP_WORDS.has(lower)) continue;
    // English identifiers (camelCase, snake_case, PascalCase) — 4+ chars
    if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(token) && token.length >= 4) {
      keywords.push(lower);
    }
    // Korean content words (3+ chars to skip particles like 에러가→에러)
    if (/[\\uAC00-\\uD7AF]/.test(token) && token.length >= 3 && !STOP_WORDS.has(token)) {
      keywords.push(token);
    }
    // File paths, module references, Error class names
    if (token.includes('/') || token.includes('.') || /Error$/.test(token)) {
      keywords.push(token);
    }
  }

  // Deduplicate and limit
  return [...new Set(keywords)].slice(0, 5);
}

try {
  const projectRoot = findProjectRoot(process.cwd());
  if (!projectRoot) process.exit(0);

  // Read user prompt from stdin
  let input = '';
  try {
    input = readFileSync('/dev/stdin', 'utf-8');
  } catch {
    process.exit(0);
  }

  let userMessage = '';
  try {
    const parsed = JSON.parse(input);
    userMessage = parsed.user_prompt || parsed.message || '';
  } catch {
    // Plain text input
    userMessage = input;
  }

  if (!userMessage || userMessage.length < 5) process.exit(0);

  const keywords = extractKeywords(userMessage);
  if (keywords.length === 0) process.exit(0);

  const raw = run(projectRoot, ['context', 'search', '--keywords', keywords.join(','), '--format', 'json']);
  const data = JSON.parse(raw);

  if (!data.results || data.results.length === 0) process.exit(0);

  const lines = [];
  lines.push('[Graph Context] Related to your query:');
  for (const r of data.results.slice(0, 5)) {
    const tag = r.type.replace('https://opentology.dev/vocab#', '');
    let line = \`- [\${tag}] \${r.title}\`;
    if (r.status) line += \` (\${r.status})\`;
    if (r.date) line += \` [\${r.date}]\`;
    lines.push(line);
    if (r.solution) lines.push(\`  Solution: \${r.solution}\`);
    if (r.reason) lines.push(\`  Reason: \${r.reason}\`);
    if (r.body && r.body.length <= 200) lines.push(\`  \${r.body}\`);
  }

  console.log(lines.join('\\n'));
} catch {
  // Silent exit — do not block prompt submission
  process.exit(0);
}
`;
}
