#!/usr/bin/env node
// Generated by: opentology context init
// PostToolUse hook (Bash) — matches error output against known patterns
import { existsSync, readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, resolve, dirname } from 'node:path';

const TIMEOUT = parseInt(process.env.OPENTOLOGY_HOOK_TIMEOUT || '3000', 10);

// Error indicators that trigger pattern search
const ERROR_PATTERNS = [
  /\bError\b/i,
  /\bERR!\b/,
  /\bFailed\b/i,
  /\bfatal\b/i,
  /\bENOENT\b/,
  /\bENOTDIR\b/,
  /\bEACCES\b/,
  /\bSyntaxError\b/,
  /\bTypeError\b/,
  /\bReferenceError\b/,
  /\bModuleNotFoundError\b/,
  /\bexited with code [1-9]/,
  /\bcommand not found\b/,
  /\bCannot find module\b/,
  /\bTS\d{4}:/,
];

function findProjectRoot(startDir) {
  let dir = resolve(startDir);
  while (dir !== dirname(dir)) {
    if (existsSync(join(dir, '.opentology.json'))) return dir;
    dir = dirname(dir);
  }
  return null;
}

function findBin(projectRoot) {
  const local = join(projectRoot, 'node_modules', '.bin', 'opentology');
  if (existsSync(local)) return { bin: local, args: [] };
  return { bin: 'npx', args: ['opentology'] };
}

function run(projectRoot, cmdArgs) {
  const { bin, args } = findBin(projectRoot);
  return execFileSync(bin, [...args, ...cmdArgs], {
    cwd: projectRoot,
    timeout: TIMEOUT,
    encoding: 'utf-8',
    stdio: ['pipe', 'pipe', 'pipe'],
  });
}

function extractErrorKeywords(output) {
  const keywords = new Set();

  // Extract error class names (TypeError, SyntaxError, etc.)
  const errorClasses = output.match(/\b[A-Z][a-zA-Z]*Error\b/g);
  if (errorClasses) errorClasses.forEach(e => keywords.add(e));

  // Extract TS error codes
  const tsCodes = output.match(/TS\d{4}/g);
  if (tsCodes) tsCodes.forEach(c => keywords.add(c));

  // Extract "Cannot find module 'xxx'"
  const modules = output.match(/Cannot find module ['"]([^'"]+)['"]/g);
  if (modules) modules.forEach(m => {
    const name = m.match(/['"]([^'"]+)['"]/)?.[1];
    if (name) keywords.add(name);
  });

  // Extract file paths from error output
  const paths = output.match(/(?:src|lib)\/[\w/.-]+\.\w+/g);
  if (paths) paths.slice(0, 3).forEach(p => keywords.add(p));

  // Extract npm package names from errors
  const npmPkgs = output.match(/(?:ERR!|error)\s+([a-z@][a-z0-9@/.-]+)/gi);
  if (npmPkgs) npmPkgs.slice(0, 2).forEach(p => {
    const name = p.replace(/^(?:ERR!|error)\s+/i, '');
    if (name.length >= 3) keywords.add(name);
  });

  return [...keywords].slice(0, 5);
}

try {
  const projectRoot = findProjectRoot(process.cwd());
  if (!projectRoot) process.exit(0);

  // Read tool output from stdin
  let input = '';
  try {
    input = readFileSync('/dev/stdin', 'utf-8');
  } catch {
    process.exit(0);
  }

  let toolOutput = '';
  let toolName = '';
  try {
    const parsed = JSON.parse(input);
    toolName = parsed.tool_name || '';
    toolOutput = parsed.tool_output || parsed.stdout || parsed.stderr || '';
  } catch {
    toolOutput = input;
  }

  // Only process Bash tool output
  if (toolName && toolName !== 'Bash') process.exit(0);

  // Check if output contains error indicators
  if (!toolOutput || toolOutput.length < 10) process.exit(0);
  const hasError = ERROR_PATTERNS.some(p => p.test(toolOutput));
  if (!hasError) process.exit(0);

  const keywords = extractErrorKeywords(toolOutput);
  if (keywords.length === 0) process.exit(0);

  const raw = run(projectRoot, [
    'context', 'search',
    '--keywords', keywords.join(','),
    '--types', 'Pattern,Issue,Knowledge',
    '--format', 'json',
  ]);
  const data = JSON.parse(raw);

  if (!data.results || data.results.length === 0) process.exit(0);

  const lines = [];
  lines.push('[Known Pattern Match] Similar errors found in project history:');
  for (const r of data.results.slice(0, 3)) {
    const tag = r.type.replace('https://opentology.dev/vocab#', '');
    lines.push(`- [${tag}] ${r.title}${r.status ? ' (' + r.status + ')' : ''}`);
    if (r.solution) lines.push(`  Solution: ${r.solution}`);
    if (r.cause) lines.push(`  Cause: ${r.cause}`);
    if (r.body && r.body.length <= 150) lines.push(`  ${r.body}`);
  }

  console.log(lines.join('\n'));
} catch {
  // Silent exit — do not block command execution
  process.exit(0);
}
