#!/usr/bin/env node
// Generated by: opentology context init
// SessionStart hook — loads project context from OpenTology graph
import { existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, resolve, dirname } from 'node:path';

const TIMEOUT = parseInt(process.env.OPENTOLOGY_HOOK_TIMEOUT || '5000', 10);

function findProjectRoot(startDir) {
  let dir = resolve(startDir);
  while (dir !== dirname(dir)) {
    if (existsSync(join(dir, '.opentology.json'))) return dir;
    dir = dirname(dir);
  }
  return null;
}

function findBin(projectRoot) {
  const local = join(projectRoot, 'node_modules', '.bin', 'opentology');
  if (existsSync(local)) return { bin: local, args: [] };
  return { bin: 'npx', args: ['opentology'] };
}

function run(projectRoot, cmdArgs) {
  const { bin, args } = findBin(projectRoot);
  return execFileSync(bin, [...args, ...cmdArgs], {
    cwd: projectRoot,
    timeout: TIMEOUT,
    encoding: 'utf-8',
    stdio: ['pipe', 'pipe', 'pipe'],
  });
}

function formatOutput(data) {
  const lines = [];
  lines.push(`## Project Context: ${data.projectId}\n`);

  if (data.sessions && data.sessions.length > 0) {
    lines.push('### Recent Sessions');
    for (const s of data.sessions) {
      lines.push(`- [${s.date}] ${s.title}`);
      if (s.nextTodo) lines.push(`  Next: ${s.nextTodo}`);
    }
    lines.push('');
  }

  if (data.openIssues && data.openIssues.length > 0) {
    lines.push(`### Open Issues (${data.openIssues.length})`);
    for (const i of data.openIssues) {
      lines.push(`- [${i.date}] ${i.title}`);
    }
    lines.push('');
  }

  if (data.recentDecisions && data.recentDecisions.length > 0) {
    lines.push('### Recent Decisions');
    for (const d of data.recentDecisions) {
      lines.push(`- [${d.date}] ${d.title}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('Dependency graph (otx:Module + otx:dependsOn) is available in the context graph.');
  lines.push('If significant code changes occurred since last scan, consider running context_scan to update dependency triples.');
  lines.push('Reminder: At session end, push a session summary using push to the sessions graph.');

  return lines.join('\n');
}

try {
  const projectRoot = findProjectRoot(process.cwd());
  if (!projectRoot) process.exit(0);

  // Step 1: Auto-sync — recover missed sessions and rescan modules
  let syncSummary = '';
  try {
    const syncRaw = run(projectRoot, ['context', 'sync', '--format', 'json']);
    const syncData = JSON.parse(syncRaw);
    const parts = [];
    if (syncData.sessionsRecovered > 0) {
      parts.push(`${syncData.sessionsRecovered} session(s) recovered from git`);
    }
    if (syncData.modulesUpdated) {
      parts.push(`modules rescanned (${syncData.moduleStats?.modules ?? 0} modules)`);
    }
    if (parts.length > 0) {
      syncSummary = 'Auto-sync: ' + parts.join(', ') + '.';
    }
  } catch {
    // Sync failed — continue with load
  }

  // Step 2: Load context
  const raw = run(projectRoot, ['context', 'load', '--format', 'json']);
  const data = JSON.parse(raw);

  const hasData = (data.sessions?.length > 0) ||
                  (data.openIssues?.length > 0) ||
                  (data.recentDecisions?.length > 0);

  if (hasData) {
    const output = formatOutput(data);
    if (syncSummary) {
      console.log(syncSummary + '\n');
    }
    console.log(output);
  } else {
    if (syncSummary) {
      console.log(syncSummary);
    }
    console.log(`OpenTology context active for ${data.projectId}. No session data yet.`);
  }
} catch {
  // Silent exit — do not block session start
  process.exit(0);
}
